import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>E-Returns</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the E-Returns Kiosk at UBC!
        </h1>

        <div className={styles.grid}>
          <a href="/start">
            <button className={styles.greenButton}>
              Start a return
            </button> 
          </a>
        </div>
      </main>
    </div>
  )
}
