import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../../styles/Home.module.css'
import OtpInput from 'react-otp-input';
import { useRouter } from 'next/router'
import { SimpleGrid, Box, Center, Heading, Text, VStack } from '@chakra-ui/react'



export default function Start() {
  const [num, setNum] = useState('');
  const router = useRouter()

  let changeNum = (e) => { 
    if (e.length == 4) { 
        router.push(`/return/${e}`)
    }
    console.log(e); 
    setNum(e);
  }
  return (
    <SimpleGrid height="80vh">
      <Head>
        <title>E-Returns</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <Center marginTop="15%">
      <VStack columns={1}>
        <Box> 
            <Heading size="4xl" textAlign="center">
                Enter the returns code you <br/> received in the email
            </Heading>
            
            <Center>
                <OtpInput
                    value={num}
                    onChange={changeNum}
                    numInputs={4}
                    separator={<span> </span>}
                    isInputNum={true}
                    inputStyle={styles.password}
                />
            </Center> 
        </Box>
      </VStack>
      </Center>
        <Box marginLeft="21.5%"> 
            <footer className={styles.footer}>
                <a href="/"> 
                    <button className={styles.grayButton}>
                        <Text> Cancel Return </Text>
                    </button>
                </a>
            </footer>
        </Box>
    </SimpleGrid>
  )
}
